pipeline{
    agent { label 'ansible'}
    stages{
        stage ('build'){
            steps {
                git url : 'https://github.com/Mypracticeclassoct-dec/january2023.git' , branch: 'main'

            }
        }
        stage ('install apache'){
            steps{
                 sh 'pwd'
                sh ' cd /january2023/31_jan_2023'
                sh 'ansible-playbook -i hosts --syntax-check main.yaml'
                sh 'ansible-playbook -i hosts main.yaml' 
            }
        }
    }
}