pipeline{
    agent { label 'ansible'}
    stages{
        stage ('build'){
            steps {
                git url : 'https://github.com/Mypracticeclassoct-dec/january2023.git' , branch: 'main'

            }
        }
        stage ('install apache'){
            steps{
                sh 'ansible-playbook -i hosts --syntax-check 31_jan_2023/main.yaml'
                sh 'ansible-playbook -i hosts 31_jan_2023/main.yaml' 
            }
        }
    }
}