---
- name: installing apache
  hosts: localhost
  become: true
  tasks:
    - name:  install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
